### ISSUE TITLE
pypi package is empty 

### ISSUE THREAD

**Issue by syphar** [dahlia/wsgi-oauth2#14]
Not sure where the problem lies. 

The `0.2.1` package on PyPI does not contain any source files. 

But when I run `python setup.py sdist` locally on the `main` branch, the resulting package seems to have everything.

**Comment by syphar** [comment]
@dahlia anything you can do here? 

Not sure what's wrong

**Comment by dahlia** [comment]
Released a [new version][1] which is fixed this.

[1]: https://pypi.org/project/wsgi-oauth2/0.2.2/

**Comment by syphar** [comment]
thank you @dahlia !
